//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    
    public partial class GradesJournalDBEntities : DbContext
    {
        private static GradesJournalDBEntities _context;
        public GradesJournalDBEntities()
            : base("name=GradesJournalDBEntities")
        {
        }

        public static GradesJournalDBEntities GetContext()
        {
            if (_context == null)
            {
                _context= new GradesJournalDBEntities();
            }
            return _context;
        }
       
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Классы> Классы { get; set; }
        public virtual DbSet<Оценки> Оценки { get; set; }
        public virtual DbSet<Предметы> Предметы { get; set; }
        public virtual DbSet<Ученики> Ученики { get; set; }
    }
}
