//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оценки
    {
        public int ID_оценки { get; set; }
        public string Оценка { get; set; }
        public string ФИО_ученика { get; set; }
        public System.DateTime Дата_оценки { get; set; }
        public string Предмет { get; set; }
    }
}
